/**
 * This class has been auto-generated by PHP-DI.
 */
class <?=$this->containerClass?> extends \DI\Container
{
    const METHOD_MAPPING = <?php var_export($this->entryToMethodMapping) ?>;

    public function get($name)
    {
        // Try to find the entry in the singleton map
        if (isset($this->singletonEntries[$name]) || array_key_exists($name, $this->singletonEntries)) {
            return $this->singletonEntries[$name];
        }

        $method = self::METHOD_MAPPING[$name] ?? null;
        if ($method !== null) {
            $value = $this->$method();
            // Store the entry to always return it without recomputing it
            $this->singletonEntries[$name] = $value;
            return $value;
        }

        return parent::get($name);
    }

    public function has($name)
    {
        if (! is_string($name)) {
            throw new InvalidArgumentException(sprintf(
                'The name parameter must be of type string, %s given',
                is_object($name) ? get_class($name) : gettype($name)
            ));
        }

        if (isset(self::METHOD_MAPPING[$name])) {
            return true;
        }

        return parent::has($name);
    }

<?php foreach ($this->methods as $methodName => $methodContent) : ?>
    private function <?=$methodName?>()
    {
        <?=$methodContent?>

    }

<?php endforeach ?>
}

return '<?=$this->containerClass?>';
